server:
  port: 9093

spring:
  profiles:
    active: dev
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cb28m4ecsnv3.us-east-1.rds.amazonaws.com:3306/userdb  # Replace 'your_database_name' with your actual database name
    username: admin  # Replace 'your_username' with your database username
    password: Ssamar143s  # Replace 'your_password' with your database password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
